/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as AuthedAdvisoryRouteImport } from './routes/_authed/advisory'
import { Route as AuthedAnnouncementsRouteImport } from './routes/_authed/announcements'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDocumentsRouteImport } from './routes/_authed/documents'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTasksRouteImport } from './routes/_authed/tasks'
import { Route as AuthedTaxRouteImport } from './routes/_authed/tax'
import { Route as AuthedTeamRouteImport } from './routes/_authed/team'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthedAccountsIdRouteImport } from './routes/_authed/accounts.$id'
import { Route as AuthedAuditIdRouteImport } from './routes/_authed/audit.$id'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedClientsIdRouteImport } from './routes/_authed/clients/$id'
import { Route as AuthedTaxTypeRouteImport } from './routes/_authed/tax.$type'
import { Route as AuthedTeamIdRouteImport } from './routes/_authed/team.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdvisoryRoute = AuthedAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnnouncementsRoute = AuthedAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsRoute = AuthedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTaxRoute = AuthedTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamRoute = AuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedAccountsIdRoute = AuthedAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAccountsRoute,
} as any)
const AuthedAuditIdRoute = AuthedAuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAuditRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIdRoute = AuthedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTaxTypeRoute = AuthedTaxTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => AuthedTaxRoute,
} as any)
const AuthedTeamIdRoute = AuthedTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthedAccountsRouteWithChildren
  '/activity': typeof AuthedActivityRoute
  '/advisory': typeof AuthedAdvisoryRoute
  '/announcements': typeof AuthedAnnouncementsRoute
  '/audit': typeof AuthedAuditRouteWithChildren
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/documents': typeof AuthedDocumentsRoute
  '/settings': typeof AuthedSettingsRoute
  '/tasks': typeof AuthedTasksRoute
  '/tax': typeof AuthedTaxRouteWithChildren
  '/team': typeof AuthedTeamRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
  '/audit/$id': typeof AuthedAuditIdRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/tax/$type': typeof AuthedTaxTypeRoute
  '/team/$id': typeof AuthedTeamIdRoute
  '/clients/': typeof AuthedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthedAccountsRouteWithChildren
  '/activity': typeof AuthedActivityRoute
  '/advisory': typeof AuthedAdvisoryRoute
  '/announcements': typeof AuthedAnnouncementsRoute
  '/audit': typeof AuthedAuditRouteWithChildren
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/documents': typeof AuthedDocumentsRoute
  '/settings': typeof AuthedSettingsRoute
  '/tasks': typeof AuthedTasksRoute
  '/tax': typeof AuthedTaxRouteWithChildren
  '/team': typeof AuthedTeamRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
  '/audit/$id': typeof AuthedAuditIdRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/tax/$type': typeof AuthedTaxTypeRoute
  '/team/$id': typeof AuthedTeamIdRoute
  '/clients': typeof AuthedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authed/accounts': typeof AuthedAccountsRouteWithChildren
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/advisory': typeof AuthedAdvisoryRoute
  '/_authed/announcements': typeof AuthedAnnouncementsRoute
  '/_authed/audit': typeof AuthedAuditRouteWithChildren
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/documents': typeof AuthedDocumentsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/tasks': typeof AuthedTasksRoute
  '/_authed/tax': typeof AuthedTaxRouteWithChildren
  '/_authed/team': typeof AuthedTeamRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authed/accounts/$id': typeof AuthedAccountsIdRoute
  '/_authed/audit/$id': typeof AuthedAuditIdRoute
  '/_authed/clients/$id': typeof AuthedClientsIdRoute
  '/_authed/tax/$type': typeof AuthedTaxTypeRoute
  '/_authed/team/$id': typeof AuthedTeamIdRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/activity'
    | '/advisory'
    | '/announcements'
    | '/audit'
    | '/calendar'
    | '/dashboard'
    | '/documents'
    | '/settings'
    | '/tasks'
    | '/tax'
    | '/team'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/accounts/$id'
    | '/audit/$id'
    | '/clients/$id'
    | '/tax/$type'
    | '/team/$id'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/activity'
    | '/advisory'
    | '/announcements'
    | '/audit'
    | '/calendar'
    | '/dashboard'
    | '/documents'
    | '/settings'
    | '/tasks'
    | '/tax'
    | '/team'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/accounts/$id'
    | '/audit/$id'
    | '/clients/$id'
    | '/tax/$type'
    | '/team/$id'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authed/accounts'
    | '/_authed/activity'
    | '/_authed/advisory'
    | '/_authed/announcements'
    | '/_authed/audit'
    | '/_authed/calendar'
    | '/_authed/dashboard'
    | '/_authed/documents'
    | '/_authed/settings'
    | '/_authed/tasks'
    | '/_authed/tax'
    | '/_authed/team'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authed/accounts/$id'
    | '/_authed/audit/$id'
    | '/_authed/clients/$id'
    | '/_authed/tax/$type'
    | '/_authed/team/$id'
    | '/_authed/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/advisory': {
      id: '/_authed/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AuthedAdvisoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/announcements': {
      id: '/_authed/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthedAnnouncementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents': {
      id: '/_authed/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthedDocumentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tax': {
      id: '/_authed/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof AuthedTaxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/team': {
      id: '/_authed/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthedTeamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accounts/$id': {
      id: '/_authed/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthedAccountsIdRouteImport
      parentRoute: typeof AuthedAccountsRoute
    }
    '/_authed/audit/$id': {
      id: '/_authed/audit/$id'
      path: '/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthedAuditIdRouteImport
      parentRoute: typeof AuthedAuditRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$id': {
      id: '/_authed/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthedClientsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tax/$type': {
      id: '/_authed/tax/$type'
      path: '/$type'
      fullPath: '/tax/$type'
      preLoaderRoute: typeof AuthedTaxTypeRouteImport
      parentRoute: typeof AuthedTaxRoute
    }
    '/_authed/team/$id': {
      id: '/_authed/team/$id'
      path: '/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof AuthedTeamIdRouteImport
      parentRoute: typeof AuthedTeamRoute
    }
  }
}

interface AuthedAccountsRouteChildren {
  AuthedAccountsIdRoute: typeof AuthedAccountsIdRoute
}

const AuthedAccountsRouteChildren: AuthedAccountsRouteChildren = {
  AuthedAccountsIdRoute: AuthedAccountsIdRoute,
}

const AuthedAccountsRouteWithChildren = AuthedAccountsRoute._addFileChildren(
  AuthedAccountsRouteChildren,
)

interface AuthedAuditRouteChildren {
  AuthedAuditIdRoute: typeof AuthedAuditIdRoute
}

const AuthedAuditRouteChildren: AuthedAuditRouteChildren = {
  AuthedAuditIdRoute: AuthedAuditIdRoute,
}

const AuthedAuditRouteWithChildren = AuthedAuditRoute._addFileChildren(
  AuthedAuditRouteChildren,
)

interface AuthedTaxRouteChildren {
  AuthedTaxTypeRoute: typeof AuthedTaxTypeRoute
}

const AuthedTaxRouteChildren: AuthedTaxRouteChildren = {
  AuthedTaxTypeRoute: AuthedTaxTypeRoute,
}

const AuthedTaxRouteWithChildren = AuthedTaxRoute._addFileChildren(
  AuthedTaxRouteChildren,
)

interface AuthedTeamRouteChildren {
  AuthedTeamIdRoute: typeof AuthedTeamIdRoute
}

const AuthedTeamRouteChildren: AuthedTeamRouteChildren = {
  AuthedTeamIdRoute: AuthedTeamIdRoute,
}

const AuthedTeamRouteWithChildren = AuthedTeamRoute._addFileChildren(
  AuthedTeamRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRouteWithChildren
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedAdvisoryRoute: typeof AuthedAdvisoryRoute
  AuthedAnnouncementsRoute: typeof AuthedAnnouncementsRoute
  AuthedAuditRoute: typeof AuthedAuditRouteWithChildren
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDocumentsRoute: typeof AuthedDocumentsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
  AuthedTaxRoute: typeof AuthedTaxRouteWithChildren
  AuthedTeamRoute: typeof AuthedTeamRouteWithChildren
  AuthedClientsIdRoute: typeof AuthedClientsIdRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRouteWithChildren,
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedAdvisoryRoute: AuthedAdvisoryRoute,
  AuthedAnnouncementsRoute: AuthedAnnouncementsRoute,
  AuthedAuditRoute: AuthedAuditRouteWithChildren,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDocumentsRoute: AuthedDocumentsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTasksRoute: AuthedTasksRoute,
  AuthedTaxRoute: AuthedTaxRouteWithChildren,
  AuthedTeamRoute: AuthedTeamRouteWithChildren,
  AuthedClientsIdRoute: AuthedClientsIdRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
