-- Advisory case classification and stable case reference.
-- Modular fix for the Advisory module: existing cases are preserved.

ALTER TABLE public.advisory_projects
  ADD COLUMN IF NOT EXISTS service_type text NOT NULL DEFAULT 'company',
  ADD COLUMN IF NOT EXISTS case_number bigint GENERATED BY DEFAULT AS IDENTITY;

-- Keep the classification limited to the service catalogue used by Advisory.
ALTER TABLE public.advisory_projects
  DROP CONSTRAINT IF EXISTS advisory_projects_service_type_check;

ALTER TABLE public.advisory_projects
  ADD CONSTRAINT advisory_projects_service_type_check
  CHECK (service_type IN ('brs','cbk','company','financial','pbora'));

CREATE UNIQUE INDEX IF NOT EXISTS advisory_projects_case_number_uidx
  ON public.advisory_projects(case_number);

-- Existing Advisory security boundaries treat service classification as protected.
-- Extend that guard to the newly introduced column without changing handler permissions.
CREATE OR REPLACE FUNCTION public.guard_advisory_case_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_admin(auth.uid()) THEN
    RETURN NEW;
  END IF;

  IF auth.uid() IS NULL OR NOT public.can_work_advisory(auth.uid()) THEN
    RAISE EXCEPTION 'You do not have permission to modify Advisory cases.' USING ERRCODE = '42501';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.client_id IS DISTINCT FROM OLD.client_id
     OR NEW.service_type IS DISTINCT FROM OLD.service_type
     OR NEW.case_number IS DISTINCT FROM OLD.case_number
     OR NEW.stage IS DISTINCT FROM OLD.stage
     OR NEW.start_date IS DISTINCT FROM OLD.start_date
     OR NEW.due_date IS DISTINCT FROM OLD.due_date
     OR NEW.created_by IS DISTINCT FROM OLD.created_by
     OR NEW.created_at IS DISTINCT FROM OLD.created_at
     OR NEW.closed_at IS DISTINCT FROM OLD.closed_at
     OR NEW.closed_by IS DISTINCT FROM OLD.closed_by
     OR NEW.closure_notes IS DISTINCT FROM OLD.closure_notes THEN
    RAISE EXCEPTION 'Only Director/Admin can change protected Advisory case fields.' USING ERRCODE = '42501';
  END IF;

  IF NEW.invoice_id IS DISTINCT FROM OLD.invoice_id AND NOT EXISTS (
    SELECT 1 FROM public.invoices i
    WHERE i.id = NEW.invoice_id
      AND i.client_id = NEW.client_id
      AND i.created_by = auth.uid()
      AND OLD.invoice_id IS NULL
  ) THEN
    RAISE EXCEPTION 'Only Director/Admin or the authorized invoice flow can change the invoice link.' USING ERRCODE = '42501';
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status
     AND (NEW.status::text = 'completed' OR OLD.status::text = 'completed') THEN
    RAISE EXCEPTION 'Only Director/Admin can change a completed Advisory case or mark a case completed until completion controls are enabled.' USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_guard_advisory_case_update ON public.advisory_projects;
CREATE TRIGGER trg_guard_advisory_case_update
BEFORE UPDATE ON public.advisory_projects
FOR EACH ROW EXECUTE FUNCTION public.guard_advisory_case_update();
